// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_8yDYlQR4cGtYtwyxyntqcnflnJ3YNug',
    appId: '1:112963158289:web:815b655cda994390ec8cb0',
    messagingSenderId: '112963158289',
    projectId: 'chat-app-932ea',
    authDomain: 'chat-app-932ea.firebaseapp.com',
    storageBucket: 'chat-app-932ea.firebasestorage.app',
    measurementId: 'G-VY8P2MNRR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnQXHqYbJcJODqMuLBV4uXmVyGGKePQwE',
    appId: '1:112963158289:android:b74b9742ca1d1cb9ec8cb0',
    messagingSenderId: '112963158289',
    projectId: 'chat-app-932ea',
    storageBucket: 'chat-app-932ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUmWTLDLJfXEFfJh8iuNhSWdCVJn_lTeM',
    appId: '1:112963158289:ios:530245cae8f45b16ec8cb0',
    messagingSenderId: '112963158289',
    projectId: 'chat-app-932ea',
    storageBucket: 'chat-app-932ea.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUmWTLDLJfXEFfJh8iuNhSWdCVJn_lTeM',
    appId: '1:112963158289:ios:530245cae8f45b16ec8cb0',
    messagingSenderId: '112963158289',
    projectId: 'chat-app-932ea',
    storageBucket: 'chat-app-932ea.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_8yDYlQR4cGtYtwyxyntqcnflnJ3YNug',
    appId: '1:112963158289:web:d75295ee8f687c17ec8cb0',
    messagingSenderId: '112963158289',
    projectId: 'chat-app-932ea',
    authDomain: 'chat-app-932ea.firebaseapp.com',
    storageBucket: 'chat-app-932ea.firebasestorage.app',
    measurementId: 'G-570RV5Q485',
  );
}
